# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
jobs:
  this_job:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: aws cloudformation deploy --stack-name create_infrastructure --template-body template.yml  --region=us-west-2 --capabilities CAPABILITY_IAM

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - this_job 
